import "./globals.css";
import { authOptions } from "./api/auth/[...nextauth]/route";
import { AppBar, Toolbar, Container, Button } from "@mui/material";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Toaster } from "react-hot-toast";
import AuthButtons from "@/components/features/auth/AuthButtons";
import NotificationsBell from "@/components/layout/NotificationsBell";
import AuthProvider from "@/components/providers/AuthProvider";
import ReduxProvider from "@/components/providers/ReduxProvider";
import ThemeRegistry from "@/components/providers/ThemeRegistry";
import Image from "next/image";
import Link from "next/link";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="pl">
      <body>
        <AuthProvider>
          <ReduxProvider>
            <ThemeRegistry>
              <Toaster position="top-right" />
              <AppBar position="static">
                <Toolbar>
                  <Link href="/" style={{ marginRight: "auto" }}>
                    <Image
                      src="/images/gig-logo.png"
                      alt="EventMates Logo"
                      width={100}
                      height={100}
                      priority
                    />
                  </Link>
                  {session && (
                    <>
                      <Button
                        component={Link}
                        href="/events/new"
                        variant="contained"
                        color="secondary"
                        sx={{ mr: 2 }}
                      >
                        Dodaj wydarzenie
                      </Button>
                      <NotificationsBell />
                    </>
                  )}{" "}
                  <AuthButtons />
                </Toolbar>
              </AppBar>
              <Container>{children}</Container>{" "}
            </ThemeRegistry>
          </ReduxProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
