import type { Metadata } from "next";
import "./globals.css";
import ThemeRegistry from "@/components/ThemeRegistry";
import AuthProvider from "@/components/AuthProvider";
import AuthButtons from "@/components/AuthButtons";
import { AppBar, Toolbar, Typography, Container } from "@mui/material";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body>
        <AuthProvider>
          <ThemeRegistry>
            <AppBar position="static">
              <Toolbar>
                <Typography variant="h6" sx={{ flexGrow: 1 }}>
                  EventMates
                </Typography>
                <AuthButtons />
              </Toolbar>
            </AppBar>
            <Container>{children}</Container>{" "}
          </ThemeRegistry>
        </AuthProvider>
      </body>
    </html>
  );
}
