import type { Metadata } from "next";
import "./globals.css";
import ThemeRegistry from "@/components/ThemeRegistry";
import AuthProvider from "@/components/AuthProvider";
import AuthButtons from "@/components/AuthButtons";
import { AppBar, Toolbar, Container } from "@mui/material";
import ReduxProvider from "@/components/ReduxProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import NotificationsBell from "@/components/NotificationsBell";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="pl">
      <body>
        <AuthProvider>
          <ReduxProvider>
            <ThemeRegistry>
              <AppBar position="static">
                <Toolbar>
                  <Link href="/" style={{ marginRight: "auto" }}>
                    <Image
                      src="/images/gig-logo.png"
                      alt="EventMates Logo"
                      width={100}
                      height={100}
                      priority
                    />
                  </Link>
                  {session && <NotificationsBell />}
                  <AuthButtons />
                </Toolbar>
              </AppBar>
              <Container>{children}</Container>{" "}
            </ThemeRegistry>
          </ReduxProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
